"""
Builds three synthetic site-visit bundles at a fictional facility, one per
checklist lens, so the demo proves the "swappable checklist" design point
for real rather than just in the README's prose:

  - Final Assembly Line   -> Lean 5S            -> mild/mostly-clean read
  - Packaging & Ship Line -> TOC constraint walk -> a real bottleneck
  - Receiving Dock        -> Safety & Compliance -> critical safety findings

No real facility's data is used anywhere in this repository. Every note,
photo, and metadata file here is synthetic, and every photo is a plain
programmatically-drawn placeholder (PIL shapes + text) -- not a stock photo
and not a real jobsite image -- generated fresh by this script, never
hand-authored or sourced from anywhere else.

Each visit's field notes deliberately include a few that DON'T match any
checklist item (an operator praising a clean station, a general "looks
fine" walkthrough note) -- a pipeline that force-matches every note to
something would be lying about its own confidence, and the demo should
show the unmatched path working, not just the happy path.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
SYNTH_DIR = ROOT / "data" / "synthetic"

SYNTHETIC_DATA_NOTE = (
    "Demo data: this facility, its field notes, and its photos are entirely synthetic, "
    "generated by scripts/generate_synthetic_data.py. No real facility's data is used."
)


def _draw_placeholder(path: Path, bg_color, label: str, sublabel: str) -> None:
    img = Image.new("RGB", (640, 480), color=bg_color)
    draw = ImageDraw.Draw(img)
    draw.rectangle([20, 20, 619, 459], outline=(30, 30, 30), width=3)
    draw.text((40, 200), label, fill=(20, 20, 20))
    draw.text((40, 230), sublabel, fill=(60, 60, 60))
    draw.text((40, 420), "synthetic placeholder image -- not a real photo", fill=(90, 90, 90))
    path.parent.mkdir(parents=True, exist_ok=True)
    img.save(path)


def _voice(note_id: str, timestamp: str, text: str) -> dict:
    return {"note_id": note_id, "kind": "voice", "timestamp": timestamp, "fixture_transcript": text}


def _photo(note_id: str, timestamp: str, filename: str, scene_description: str, expected_item: str | None) -> dict:
    return {
        "note_id": note_id, "kind": "photo", "timestamp": timestamp,
        "image_path": f"photos/{filename}",
        "fixture_caption": {"scene_description": scene_description, "expected_checklist_item": expected_item},
    }


# ---------------------------------------------------------------------------
# Visit A: Final Assembly Line -- Lean 5S
# ---------------------------------------------------------------------------

def build_visit_a():
    slug = "final_assembly_5s"
    visit_dir = SYNTH_DIR / slug
    notes = [
        _voice("A01", "2026-09-08T08:03:00", "At workstation 3 there's a pile of old fixtures and obsolete tooling that hasn't been used in months, just sitting in the corner."),
        _voice("A02", "2026-09-08T08:07:00", "Workstation 4 has the same issue, a stack of unused brackets nobody has touched recently, kind of just junk building up."),
        _voice("A03", "2026-09-08T08:11:00", "Near the torque wrench station, tools are just tossed on the bench, no shadow board, so operators can't tell what's missing."),
        _photo("A04", "2026-09-08T08:14:00", "a04_tool_bench.png", "Tool bench for workstation 5 with several hand tools loose on the surface, no outlines or labeled spots visible.", "5s_set_in_order"),
        _voice("A05", "2026-09-08T08:18:00", "Found a bin of small hardware with no designated spot near sub-assembly, hard to tell what's supposed to go there."),
        _voice("A06", "2026-09-08T08:23:00", "Floor near the conveyor at station 2 has some grease residue that hasn't been wiped up in a while."),
        _photo("A07", "2026-09-08T08:26:00", "a07_shelf_dust.png", "Dust buildup visible on the top of a shelving unit near the receiving-side racking.", "5s_shine"),
        _voice("A08", "2026-09-08T08:31:00", "Workstation 6's layout is set up completely differently than workstation 5, even though they're doing the identical sub-assembly step, no posted standard to explain why."),
        _voice("A09", "2026-09-08T08:35:00", "Checked the 5S standard sheet posted at station 3, it's dated over a year ago, doesn't match what's actually set up now."),
        _voice("A10", "2026-09-08T08:40:00", "Asked the lead whether the daily 5S checklist gets filled out, they said honestly it's usually only completed right before a scheduled audit."),
        _voice("A11", "2026-09-08T08:44:00", "Self-audit log at station 4 has gaps, several days in a row with no entry."),
        _voice("A12", "2026-09-08T08:48:00", "Station 1 looks great honestly, tools all in their shadow board spots, clearly marked, nothing out of place."),
        _voice("A13", "2026-09-08T08:52:00", "Also noticed a second pile near receiving, mostly unused packaging materials nobody's claimed, more clutter along that wall."),
        _photo("A14", "2026-09-08T08:55:00", "a14_fixture_cart.png", "Obsolete fixture cart parked against the wall near final assembly, clearly not in current use.", "5s_sort"),
        _voice("A15", "2026-09-08T08:59:00", "Station 5's shadow board actually looks solid, every wrench has an outline and they're all present."),
        _voice("A16", "2026-09-08T09:04:00", "Walked the whole line end to end, roughly consistent about 80 percent of stations, a few outliers like station 6 stand out."),
    ]
    _draw_placeholder(visit_dir / "photos" / "a04_tool_bench.png", (222, 226, 230), "Workstation 5 -- Tool Bench", "loose hand tools, no shadow board outlines")
    _draw_placeholder(visit_dir / "photos" / "a07_shelf_dust.png", (214, 210, 198), "Receiving-Side Racking", "visible dust buildup on shelf top")
    _draw_placeholder(visit_dir / "photos" / "a14_fixture_cart.png", (200, 200, 205), "Final Assembly Wall", "obsolete fixture cart, unused")

    (visit_dir / "notes.json").write_text(json.dumps(notes, indent=2))
    (visit_dir / "visit_config.json").write_text(json.dumps({
        "facility_name": "Meridian Fabrication Works",
        "visit_area": "Final Assembly Line",
        "visit_date": "2026-09-08",
        "engagement_description": (
            "Quarterly workplace organization walk of the final assembly line, checking "
            "whether 5S standards are holding."
        ),
        "synthetic_data_note": SYNTHETIC_DATA_NOTE,
    }, indent=2))


# ---------------------------------------------------------------------------
# Visit B: Packaging & Ship Line -- Theory of Constraints
# ---------------------------------------------------------------------------

def build_visit_b():
    slug = "packaging_ship_toc"
    visit_dir = SYNTH_DIR / slug
    notes = [
        _voice("B01", "2026-09-10T07:15:00", "There's a serious backlog in front of the shrink-wrap station, totes are piled up three deep waiting for it to catch up."),
        _voice("B02", "2026-09-10T07:20:00", "Same thing an hour later, still a queue building up in front of shrink-wrap, hasn't cleared since this morning."),
        _photo("B03", "2026-09-10T07:24:00", "b03_shrinkwrap_queue.png", "Pallets of totes queued up directly in front of the shrink-wrap machine, stacked higher than the machine itself.", "toc_identify_constraint"),
        _voice("B04", "2026-09-10T07:30:00", "Shrink-wrap machine went down for a changeover for almost twenty minutes right in the middle of the backlog, operators said they didn't have the next roll staged ahead of time."),
        _voice("B05", "2026-09-10T07:36:00", "Another shrink-wrap stoppage, waiting on a part -- a replacement roll of film that wasn't staged nearby, probably ten minutes lost."),
        _voice("B06", "2026-09-10T07:42:00", "Meanwhile the labeling station upstream is running ahead, building a stack of labeled totes that shrink-wrap can't keep up with, so they're just sitting there taking up floor space."),
        _voice("B07", "2026-09-10T07:47:00", "Same thing at the case-pack step before that, running well ahead, building excess wip upstream that's just going to sit until shrink-wrap clears."),
        _voice("B08", "2026-09-10T07:53:00", "Supervisor mentioned they've talked about adding a second shrink-wrap machine before the holiday peak but it hasn't been approved yet."),
        _voice("B09", "2026-09-10T07:58:00", "One of the leads floated wanting to cross-train a picker to help run a second shrink-wrap head when volume spikes, but nobody's been trained yet."),
        _voice("B10", "2026-09-10T08:04:00", "Talked to the shift lead, they said last month the real slow point was actually the case-erector -- used to be the bottleneck there -- but that's caught up now and shrink-wrap is the one falling behind."),
        _voice("B11", "2026-09-10T08:09:00", "Walked the receiving end of this line just to check, no backlog there, that part's running fine."),
        _photo("B12", "2026-09-10T08:13:00", "b12_empty_conveyor.png", "Empty conveyor section between the label station and shrink-wrap, no product moving through, consistent with operators' reports of waiting on shrink-wrap.", "toc_identify_constraint"),
        _voice("B13", "2026-09-10T08:18:00", "No safety issues to report on this walk, just the flow issue at shrink-wrap."),
        _voice("B14", "2026-09-10T08:22:00", "Quick note: inventory count near shrink-wrap looked accurate, no discrepancy there."),
        _voice("B15", "2026-09-10T08:40:00", "Followed up at end of shift, the queue in front of shrink-wrap was still four totes deep, hadn't cleared by end of day."),
        _photo("B16", "2026-09-10T08:43:00", "b16_endofshift_queue.png", "End-of-shift photo showing totes still queued at the shrink-wrap infeed.", "toc_identify_constraint"),
    ]
    _draw_placeholder(visit_dir / "photos" / "b03_shrinkwrap_queue.png", (230, 210, 190), "Shrink-Wrap Infeed", "pallets queued, stacked above machine height")
    _draw_placeholder(visit_dir / "photos" / "b12_empty_conveyor.png", (210, 218, 224), "Label -> Shrink-Wrap Conveyor", "empty section, no product moving")
    _draw_placeholder(visit_dir / "photos" / "b16_endofshift_queue.png", (228, 205, 185), "Shrink-Wrap Infeed -- End of Shift", "queue still present at shift end")

    (visit_dir / "notes.json").write_text(json.dumps(notes, indent=2))
    (visit_dir / "visit_config.json").write_text(json.dumps({
        "facility_name": "Meridian Fabrication Works",
        "visit_area": "Packaging & Ship Line",
        "visit_date": "2026-09-10",
        "engagement_description": (
            "Walk the packaging-to-ship line to find where product is backing up before the "
            "holiday peak -- basically, find the bottleneck."
        ),
        "synthetic_data_note": SYNTHETIC_DATA_NOTE,
    }, indent=2))


# ---------------------------------------------------------------------------
# Visit C: Receiving Dock -- Safety & Compliance
# ---------------------------------------------------------------------------

def build_visit_c():
    slug = "receiving_dock_safety"
    visit_dir = SYNTH_DIR / slug
    notes = [
        _voice("C01", "2026-09-12T13:02:00", "Right where the roller conveyor meets the sorter there's an exposed pinch point, no guard around it at all."),
        _voice("C02", "2026-09-12T13:07:00", "Checked again on the other side of the dock, same conveyor line further down, another spot where the guard removed -- looks like it was taken off for maintenance and never put back."),
        _photo("C03", "2026-09-12T13:10:00", "c03_pinch_point.png", "Close-up of the conveyor transfer point showing the guard panel missing, chain and rollers exposed at hand height.", "safety_machine_guarding"),
        _voice("C04", "2026-09-12T13:15:00", "Two pallets are stacked directly in front of the east-wall emergency exit door, essentially an obstructed exit that wouldn't fully open if someone needed it."),
        _voice("C05", "2026-09-12T13:19:00", "Fire extinguisher near the dock office has an inspection tag showing the extinguisher expired six months ago."),
        _photo("C06", "2026-09-12T13:22:00", "c06_exit_blocked.png", "Emergency exit signage at the east wall dock door, view partially obstructed by stacked pallets in the foreground.", "safety_egress"),
        _voice("C07", "2026-09-12T13:27:00", "A couple of the dock workers unloading the trailer this morning had no gloves on despite the posted PPE requirement for that zone."),
        _voice("C08", "2026-09-12T13:31:00", "Saw at least one person on the dock without safety glasses near the strapping area, that's a required PPE zone too."),
        _voice("C09", "2026-09-12T13:35:00", "Forklift operator wasn't wearing a hard hat while under the mezzanine overhang, that's marked as a hard-hat zone."),
        _voice("C10", "2026-09-12T13:40:00", "Noticed a frayed cord running across the main walkway near the scale, definitely a trip hazard and an electrical one."),
        _voice("C11", "2026-09-12T13:44:00", "There's a spill near the dock plate, looked like hydraulic fluid, hasn't been cleaned up or marked off."),
        _voice("C12", "2026-09-12T13:48:00", "Cabling for the label printer runs straight across the walkway by receiving desk 2, another trip hazard."),
        _voice("C13", "2026-09-12T13:53:00", "Watched someone repeatedly doing an awkward lift straight from the trailer floor to a pallet, no lift table staged there."),
        _voice("C14", "2026-09-12T13:57:00", "No lift assist available anywhere near the dock for the heavier cases, seems like an ergonomics gap."),
        _voice("C15", "2026-09-12T14:02:00", "Evacuation map posted near the office door looks outdated, references a layout that doesn't match the current dock configuration."),
        _voice("C16", "2026-09-12T14:06:00", "A couple of chemical containers near the wash station don't have current labels on them, an unlabeled chemical situation."),
        _voice("C17", "2026-09-12T14:10:00", "Talked to the dock lead about last week's incident report, they said it involved a forklift and that same conveyor transfer area, consistent with what we're seeing here."),
        _voice("C18", "2026-09-12T14:14:00", "Rest of the dock looked reasonably organized, no other issues to flag beyond what's already noted."),
    ]
    _draw_placeholder(visit_dir / "photos" / "c03_pinch_point.png", (200, 190, 190), "Conveyor Transfer Point", "guard panel missing, rollers exposed")
    _draw_placeholder(visit_dir / "photos" / "c06_exit_blocked.png", (205, 195, 195), "East Wall Emergency Exit", "pallets partially obstructing exit view")

    (visit_dir / "notes.json").write_text(json.dumps(notes, indent=2))
    (visit_dir / "visit_config.json").write_text(json.dumps({
        "facility_name": "Meridian Fabrication Works",
        "visit_area": "Receiving Dock",
        "visit_date": "2026-09-12",
        "engagement_description": (
            "Safety and compliance walk of the receiving dock after a near-miss report."
        ),
        "synthetic_data_note": SYNTHETIC_DATA_NOTE,
    }, indent=2))


def main():
    if SYNTH_DIR.exists():
        shutil.rmtree(SYNTH_DIR)
    build_visit_a()
    build_visit_b()
    build_visit_c()
    print(f"Synthetic field visits written to {SYNTH_DIR}")


if __name__ == "__main__":
    main()
